apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: whodis
  namespace: appsec
  labels:
    team: appsec
spec:
  image: {{image}}
  port: 8080
  liveness:
    initialDelay: 60
    path: /internal/isalive
  readiness:
    initialDelay: 60
    path: /internal/isready
  replicas:
    max: 2
    min: 2
  resources:
    limits:
      memory: 300Mi
    requests:
      cpu: 50m
      memory: 50Mi
  observability:
    logging:
      destinations:
        - id: loki
    autoInstrumentation:
      enabled: true
      runtime: sdk
  prometheus:
    enabled: true
    path: /internal/metrics
  env:
    - name: GIN_MODE
      value: release
    - name: GITHUB_TEAMS_TO_SKIP
      value: nais-billing,isoc,appsec,security-managers
  envFrom:
    - secret: whodis
  accessPolicy:
    outbound:
      rules:
        - application: team-catalog-backend
          namespace: org
      external:
        - host: console.nav.cloud.nais.io
    inbound:
      rules:
        - application: tpt-graph
        - application: secretsnotifier
